services:
  - type: web
    name: todo-backend
    env: node
    region: oregon
    plan: free
    healthCheckPath: /api
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://kukkapilla2003:Rithwhick123@todo.pycijt4.mongodb.net/todo
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN_URL
        value: ${RENDER_TODO_FRONTEND_EXTERNAL_URL}

  - type: web  # ✅ Treat frontend as web service
    name: todo-frontend
    env: static  # ✅ Special "static" environment for frontend build
    # region: oregon # Removed: Static sites (or services acting as such) cannot have a region
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build  # ✅ required to serve static files
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: ${RENDER_TODO_BACKEND_EXTERNAL_URL}
